/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ../public/logo2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/logo2.glb')
  return (
    <group {...props} dispose={null} >
      <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.003']} position={[-0.2, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} scale={[40, 15, 40]}>
        <shaderMaterial vertexShader={shader.vertexShader} fragmentShader={shader.fragmentShader} />
      </mesh>
    </group >
  )
}

useGLTF.preload('/logo2.glb')


const shader = {
  vertexShader: `
      varying vec2 vUv;
      void main() {
        vUv = uv;
        gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
      }
    `,
  fragmentShader: `
      void main() {
        gl_FragColor = vec4(.95,.80,0.0,1.0);
      }
    `,
};

